language: c
sudo: false
env:
  matrix:
  - PYVERSION=2
  - PYVERSION=3
os:
- linux
- osx
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install check; fi
install:
- wget https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py
- python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 $PYVERSION --without-obvci && source ~/miniconda/bin/activate root
- conda install -q -y conda-build
script:
- CONDA_OUTPUT=$(conda build spiceypy -q --no-anaconda-upload --output)
- echo $CONDA_OUTPUT
after_script:
- if [[ ( "$TRAVIS_PULL_REQUEST" == 'false' ) && ( "$TRAVIS_BRANCH" == 'master' ) ]] ; then anaconda -t ${BINSTAR_TOKEN} upload ${CONDA_OUTPUT} -u travis --force; fi
