sudo: false
language: c
env:
  global:
    secure: O0Dh5cuNtpYcuDgbNlzg+B+vS9Opu48pLwFRy8/WVYD2uhV0sRe3ktIAFv+rdtOxziHAb/DRCax6rXDgcr7Sz+Pdzc6f3Zabko989BQlWmZJPm/KzKIKCtgfsFRjlZtk8tuKVmUoanszKe+4w2lFoWqSR1NPXbvb/3DOwjnfxgw+arX3R1bw89mj144GVeEK4lbzOFs2bTfbljAy8AK+cbAvUKPw8L0R3KShliuRkfAb2lx+ZccvSOUT4nbDPOstMfhQt+tO4TYnr5KufQy0MVgVt2PVT8t6NEdSnTN9VQzBm1qvHepu8Wgm/gzQtFmRoDG0kY39x3A8P32wPhAer0mbjY+DOfOlf+eB780anEj7vBw6N0eahhRTr4Hlgp0iXhftbDphSD2KnfMQ7l0FlkEZOW8eo0O1QqrWhj6cgnKgmLLFg/h4sf6Z8s9AccYepnlUt/bXPvkbQ5L5Z/8LImg3wLm19QND69WzA3X2rnLwXS6LG84aOI7ilZpRBLf6dhjgFQK8mCmrEN0Wu2EERtCZTFYYW9XNvQyBlcGtSYLw3pXMREDW58cMHn4RwrC5xsWsgVRPppekK9sZuqQDNhRVq+9LFMTXfXagEijbZZ+WSc/VcgT1DZeoKbfkmbcFPatamE/L2Wf/ueqAhm3OO4WYxPP88YFExHiV3TxStvc=
matrix:
  include:
  - os: linux
    dist: trusty
    env: PYVERSION=2
  - os: linux
    dist: trusty
    env: PYVERSION=3
  - os: osx
    env: PYVERSION=2
  - os: osx
    env: PYVERSION=3
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install check; fi
install:
- wget https://raw.githubusercontent.com/AndrewAnnex/Obvious-CI/fix_for_py2/bootstrap-obvious-ci-and-miniconda.py
- python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 $PYVERSION --without-obvci && source ~/miniconda/bin/activate root
- conda install -q -y conda-build
- conda install -q -y anaconda-client
script:
- conda build spiceypy -q --no-anaconda-upload
- CONDA_OUTPUT=$(conda build spiceypy -q --no-anaconda-upload --output)
- echo $CONDA_OUTPUT
- echo $(wc -c < "$CONDA_OUTPUT")
after_script:
- if [[ ( "$TRAVIS_PULL_REQUEST" == 'false' ) && ( "$TRAVIS_BRANCH" == 'master' ) ]]; then ~/miniconda/bin/anaconda -t ${BINSTAR_TOKEN} upload ${CONDA_OUTPUT} -u andrewannex; fi
