language: c
sudo: false
env:
  matrix:
  - PYVERSION=2
  - PYVERSION=3
  global:
    secure: VTodl8IqeJOxdOWv0aUywuNw35A2yLd6NkiBmOuDGb0c+Wrc8a4eK+8ks9BbF9sG3RdX7BijvoxhYgujFfrZ2+6/ljsp/55z0mPRZxnZ4vFSAhv8CiBZSIUBubXPq2Q+ZFokCq2zoBe7TLgM8Yi3qQphCgzDWdBKBNow+YkKxp8CW9C8JtvSKsQIoxamfycrbMeNW6+0xAk16b2rnUGS6HUgQg2cV/tdG7mhvvfWVjOjJqGcGq27IZTDP0us/koy/CxX9660Jl4t4RS5vBA42MC698saODgI0eDaakGDhosQUXhnka2mJGsl0s11uZS8m1gYmB4bF2uOfETaG8jDZhwId0ytjWFP5xWqZjXrSURKx8bBEOXLlmtk2BjttIqJKRBBDh+LhUxABNvLFnqsk7uVZjQLi0iisTKhSG/LJEQVODPjJd/NYZNg1YPSqVrkCCxmrdjWfW+gIcLbX8SKe2bQwAumQAJa6rN8h8uZPT+3AmP10XWTvmuVhPJsKcVrGmlmgJsuy2qy0W72OBJvXrLihXHbfN0DHbkScnvoSJD46eE3NjU60t3npZ96mjTSQ6CrAjrxIBz/pTCqZE0WJj6QWelvppYeR0hBJ1ubfwPocvTRqqWp9ZoYv+zLD5XOwteXEL4HI6f+VD1WcOAjbeaosiGVaS88EF3Qs/kTmNk=
os:
- linux
- osx
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install check; fi
install:
- wget https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py
- python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 $PYVERSION --without-obvci && source ~/miniconda/bin/activate root
- conda install -q -y conda-build
- conda install -q -y anaconda-client
- conda install -q -y anaconda-build
script:
- conda build spiceypy -q --no-anaconda-upload
- CONDA_OUTPUT=$(conda build spiceypy -q --no-anaconda-upload --output)
- echo $CONDA_OUTPUT
- echo $(wc -c < "$CONDA_OUTPUT")
after_script:
- if [[ ( "$TRAVIS_PULL_REQUEST" == 'false' ) && ( "$TRAVIS_BRANCH" == 'master' ) ]] ; then ~/miniconda/bin/anaconda -t ${BINSTAR_TOKEN} upload ${CONDA_OUTPUT} -u travis; fi
