# AppVeyor.com is a Continuous Integration service to build and run tests under Windows
# This yml file was made in part by looking at the yml files for conda and astropy.

# This is not a .NET project, so we build SpiceyPy in the install step.
build: off

environment:

  matrix:
      - PYTHON: "C:\\Python27"
        CONDA: "C:\\Miniconda"
        CONDA_BUILDS: C:\\Miniconda\conda-bld\win-32
        PYTHON_VERSION: "2.7.x"
        ARCH: "32"
        PLAT_NAME: "win32"
        PY_TAG: "cp27"

      - PYTHON: "C:\\Python27-x64"
        CONDA: "C:\\Miniconda-x64"
        CONDA_BUILDS: C:\\Miniconda-x64\conda-bld\win-64
        PYTHON_VERSION: "2.7.x"
        ARCH: "64"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp27"

      - CONDA: "C:\\Miniconda35"
        CONDA_BUILDS: C:\\Miniconda35\conda-bld\win-32
        PYTHON_VERSION: "3.5.x"
        ARCH: "32"
        WINDOWS_SDK_VERSION: "v7.1"
        PLAT_NAME: "win32"
        PY_TAG: "cp35"

      - PYTHON: "C:\\Python35-x64"
        CONDA: "C:\\Miniconda35-x64"
        CONDA_BUILDS: C:\\Miniconda35-x64\conda-bld\win-64
        PYTHON_VERSION: "3.5.x"
        ARCH: "64"
        WINDOWS_SDK_VERSION: "v7.1"
        PLAT_NAME: "win-amd64"
        PY_TAG: "cp35"

platform:
  - x64

install:
  # I think setting the path below is redundant
  # - set PATH=%CONDA%;%CONDA%/Scripts;%CONDA%/Library/bin;%PATH%
  # Update to a known good conda, found from https://github.com/numba/numba/blob/master/appveyor.yml
  # (to workaround http://help.appveyor.com/discussions/problems/4910)
  - "conda install -q -y conda=4.1.4"
  - "conda install -q -y conda-build anaconda-client anaconda-build"
  - "set CONDA_OUTPUT=$(conda build spiceypy -q --no-anaconda-upload --output)"
  - ps: ls $env:CONDA_OUTPUT
  - set PATH=%BK_PATH%

